CREATE TABLE IF NOT EXISTS cities_encore (
    id SERIAL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS urls_encore (
    id SERIAL PRIMARY KEY,
    url TEXT UNIQUE NOT NULL,
    is_processed BOOLEAN DEFAULT FALSE,
    city_id INTEGER REFERENCES cities_encore (id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);